# Generated by Django 4.2.7 on 2023-11-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('label', models.CharField(max_length=1)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
